name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'Action'
        required: true
        
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: python greeting.py ${{ inputs.name }}
